### PR TITLE
Reliability tests

### PR DESCRIPTION
**Pull request by hansl**
This is based on #77. I'll rebase once that PR is merged.

### CODE REVIEW

**Review by fmorency — CHANGES_REQUESTED** [review]
`.gitmodules` is missing; I can't test this.

**Comment by hansl** [comment]
@fmorency PTAL, I moved the files directly in our repo. They haven't changed in years and no reason to keep a submodules around.

**Review by fmorency — APPROVED** [review]
Code LGTM.

However, I can't test this properly due to #69. I will not hold the merge for it, since @brohamgoham already approved/tested it.

**Comment by fmorency** [comment]
I will be able to test once #86 is merged.

**Pull request merged**
